# `sheldon` configuration file
# ----------------------------
#
# You can modify this file directly or you can use one of the following
# `sheldon` commands which are provided to assist in editing the config file:
#
# - `sheldon add` to add a new plugin to the config file
# - `sheldon edit` to open up the config file in the default editor
# - `sheldon remove` to remove a plugin from the config file
#
# See the documentation for more https://github.com/rossmacarthur/sheldon#readme

shell = "zsh"

[plugins]

# The following definitions from the .gitconfig file need to be commented out the first time it is started:
# [url "git@github.com:"]
#   insteadOf  = https://github.com/

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.fast-syntax-highlighting]
github = 'zdharma/fast-syntax-highlighting'

[plugins.fzf-tab]
github = 'Aloxaf/fzf-tab'

# For example:
#
# [plugins.base16]
# github = "chriskempson/base16-shell"
